export const eventUserConstants = {

    GET_EVENTS_REQUEST: 'GET_EVENTS_REQUEST',
    GET_EVENTS_SUCCESS: 'GET_EVENTS_SUCCESS',
    GET_EVENTS_FAILURE: 'GET_EVENTS_FAILURE',

    DELETE_EVENTS_REQUEST: 'DELETE_EVENTS_REQUEST',
    DELETE_EVENTS_SUCCESS: 'DELETE_EVENTS_SUCCESS',
    DELETE_EVENTS_FAILURE: 'DELETE_EVENTS_FAILURE',

    CREATE_EVENTS_REQUEST: 'CREATE_EVENTS_REQUEST',
    CREATE_EVENTS_SUCCESS: 'CREATE_EVENTS_SUCCESS',
    CREATE_EVENTS_FAILURE: 'CREATE_EVENTS_FAILURE',

    GET_EVENT_REQUEST: 'GET_EVENT_REQUEST',
    GET_EVENT_SUCCESS: 'GET_EVENT_SUCCESS',
    GET_EVENT_FAILURE: 'GET_EVENT_FAILURE',

    UPDATE_EVENT_REQUEST: 'UPDATE_EVENT_REQUEST',
    UPDATE_EVENT_SUCCESS: 'UPDATE_EVENT_REQUEST',
    UPDATE_EVENT_FAILURE: 'UPDATE_EVENT_FAILURE',
}