export const eventGroupConstants = {

    GET_GROUP_EVENTS_REQUEST: 'GET_GROUP_EVENTS_REQUEST',
    GET_GROUP_EVENTS_SUCCESS: 'GET_GROUP_EVENTS_SUCCESS',
    GET_GROUP_EVENTS_FAILURE: 'GET_GROUP_EVENTS_FAILURE',

    DELETE_GROUP_EVENTS_REQUEST: 'DELETE_GROUP_EVENTS_REQUEST',
    DELETE_GROUP_EVENTS_SUCCESS: 'DELETE_GROUP_EVENTS_SUCCESS',
    DELETE_GROUP_EVENTS_FAILURE: 'DELETE_GROUP_EVENTS_FAILURE',

    CREATE_GROUP_EVENTS_REQUEST: 'CREATE_GROUP_EVENTS_REQUEST',
    CREATE_GROUP_EVENTS_SUCCESS: 'CREATE_GROUP_EVENTS_SUCCESS',
    CREATE_GROUP_EVENTS_FAILURE: 'CREATE_GROUP_EVENTS_FAILURE',

    GET_GROUP_EVENT_REQUEST: 'GET_GROUP_EVENT_REQUEST',
    GET_GROUP_EVENT_SUCCESS: 'GET_GROUP_EVENT_SUCCESS',
    GET_GROUP_EVENT_FAILURE: 'GET_GROUP_EVENT_FAILURE',

    UPDATE_GROUP_EVENT_REQUEST: 'UPDATE_GROUP_EVENT_REQUEST',
    UPDATE_GROUP_EVENT_SUCCESS: 'UPDATE_GROUP_EVENT_REQUEST',
    UPDATE_GROUP_EVENT_FAILURE: 'UPDATE_GROUP_EVENT_FAILURE',
}