export const groupsConstants = {

    GET_GROUPS_REQUEST: 'GET_GROUPS_REQUEST',
    GET_GROUPS_SUCCESS: 'GET_GROUPS_SUCCESS',
    GET_GROUPS_FAILURE: 'GET_GROUPS_FAILURE',

    CREATE_GROUP_REQUEST: 'CREATE_GROUP_REQUEST',
    CREATE_GROUP_SUCCESS: 'CREATE_GROUP_SUCCESS',
    CREATE_GROUP_FAILURE: 'CREATE_GROUP_FAILURE',

    DELETE_GROUP_REQUEST: 'DELETE_GROUP_REQUEST',
    DELETE_GROUP_SUCCESS: 'DELETE_GROUP_SUCCESS',
    DELETE_GROUP_FAILURE: 'DELETE_GROUP_FAILURE',

}