export const userConstants = {
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    LOGOUT: 'USER_LOGOUT',

    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    GET_EVENTS_REQUEST: 'GET_EVENTS_REQUEST',
    GET_EVENTS_SUCCESS: 'GET_EVENTS_SUCCESS',
    GET_EVENTS_FAILURE: 'GET_EVENTS_FAILURE',

    DELETE_EVENTS_REQUEST: 'DELETE_EVENTS_REQUEST',
    DELETE_EVENTS_SUCCESS: 'DELETE_EVENTS_SUCCESS',
    DELETE_EVENTS_FAILURE: 'DELETE_EVENTS_FAILURE',

    CREATE_EVENTS_REQUEST: 'CREATE_EVENTS_REQUEST',
    CREATE_EVENTS_SUCCESS: 'CREATE_EVENTS_SUCCESS',
    CREATE_EVENTS_FAILURE: 'CREATE_EVENTS_FAILURE',
}