# Generated by Django 3.0 on 2020-09-29 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=45, verbose_name='nazwa')),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
                ('description', models.TextField(max_length=255, verbose_name='description')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='GroupEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calendar_api.Event')),
            ],
            options={
                'verbose_name': 'group event',
                'verbose_name_plural': 'groups events',
            },
            bases=('calendar_api.event',),
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calendar_api.Event')),
            ],
            options={
                'verbose_name': 'user event',
                'verbose_name_plural': 'users events',
            },
            bases=('calendar_api.event',),
        ),
    ]
